# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170824_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_level',
            field=models.BooleanField(default=True),
        ),
    ]
